import Head from 'next/head'
import Image from 'next/image'

import { Home, Project, Skill, Contact } from '../components'

export default function HomePage() {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      <Project />
      <Skill />
      <Contact />
    </>
  )
}
